algo_hr_btc:
  BTC_HR_API_KEY: z48Hef0nYVzPROPyW0
  BTC_HR_SECRET_KEY: a2eFJ7gJ4sBo1XOOEoofMqw9SXIAK40VXhdk

algo_hr_eth:
  ETH_HR_API_KEY: cpQlgIieMmlTQ7elng
  ETH_HR_SECRET_KEY: EIJX8o4QPdu6lmSYjKt3Su0XkYAANMjJc30M

grassnode:
  GN_API: 2wlOd0ApVQgg4SDPqFk2Lq2Btku

tg_bot:
  TOKEN: 8198276230:AAETb0a9FMrRBd1IGn3XtiWFfOuwHVpgf3Y
  GROUP_ID: 8394621040